### ISSUE TITLE
should we make build.sh more common ?

### ISSUE THREAD

**Issue by chipitsine** [openresty/echo-nginx-module#46]
module echo-nginx-module usually added to stock nginx.
however, build.sh compiles nginx without many common modules, i.e. --without-http_autoindex_module, --without-http_auth_basic_module, ....

I suggest to remove those "without"s in order to make test closer to what people usually do with nginx.

**Comment by agentzh** [comment]
@chipitsine Those options are important since we want to ensure that ngx_echo does not accidentally depend on any standard nginx modules that can be disabled. See pull request #42 for such a real-world example issue.

**Comment by chipitsine** [comment]
ok, it does make sense to test that way
