### ISSUE TITLE
是不是不支持 nginx/1.9.14 版本？

### ISSUE THREAD

**Issue by taolive** [openresty/echo-nginx-module#48]
下载了：echo-nginx-module-0.59rc1.tar 文件
安装模块步骤：
./configure  --prefix=/usr/local/appsoft/nginx/app --with-http_ssl_module --with-http_image_filter_module --add-module=/usr/local/appsoft/nginx/modules/echo-nginx-module
make、make install，
并复制了objs下的nginx到/usr/local/appsoft/nginx/app/sbin目录

使用nginx -V，提示如下：
configure arguments: --prefix=/usr/local/appsoft/nginx/app --with-http_ssl_module --with-http_image_filter_module --add-module=/usr/local/appsoft/nginx/modules/echo-nginx-module

说明已经安装成功，在nginx.conf中使用echo
location / {
                echo "---------------------start-----------------";
                root   html;
                index  index.html index.htm;
                echo "--------------------------HELLO-----------------------------------";
        }

访问ningx，nginx的页面正常打开，但是在nginx的日志文件及浏览器的响应信息中，具没有看到echo输出的内容，请问下是不是安装不正确还是？

**Comment by taolive** [comment]
全部重新安装nginx及模块后，
location / {
            root   html;
            index  index.html index.htm;
           echo "-----------nginx--------hello";
        }

如上配置后，再访问nginx，则浏览器弹出下载
当屏蔽echo后：
location / {
            root   html;
            index  index.html index.htm;
           #echo "-----------nginx--------hello";
        }

则nginx页面可以正常访问

**Comment by agentzh** [comment]
@taolive Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Regarding your question, you should configure the line

```nginx
default_type text/plain;
```

to generate a proper `Content-Type` response header for your location. See

http://nginx.org/en/docs/http/ngx_http_core_module.html#default_type

for more details.

**Comment by sleep-cat** [comment]
@agentzh Thank you for your answer and solved my problem.I modified the configuration like this.
```
location /admin/ {
  default_type text/plain;
  echo "hello admin";
}
```

**Comment by agentzh** [comment]
Consider it resolved.
