### ISSUE TITLE
echo_sleep with proxy_pass - no result if echo sleep before; no delay if echo_sleep after proxy_pass

### ISSUE THREAD

**Issue by mvreg** [openresty/echo-nginx-module#5]
Please check example below... it returns different results or timing in any of tests below:
-example 1 - testfast uses no echo-nginx-module specific commands... 
-example 2 - testslow uses echo_sleep after proxy_pass.... no result text is sent to client, timing is ok
-example 3 - testslow2 uses echo_sleep before proxy_pass.... result text is ok, however timing is wrong.

You will find "Hello Worls in CURL response in example 1 and 3, but not in 2. In example 3 result returns without echo_sleep.

nginx .conf file:
location /testfast {
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_pass http://ad-emea.demodomain.net/testdirect.ashx;
}

location /testslow {
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_pass http://ad-emea.demodomain.net/testdirect.ashx;
echo_sleep 5.000;
}

location /testslow2 {
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
echo_sleep 5.000;
proxy_pass http://ad-emea.demodomain.net/testdirect.ashx;
}

testing using curl: (all 3 above examples)... upstream server is always the same... returns 200 "Hello World"

curl --verbose http://ad-emea.demodomain.net/testfast
- About to connect() to ad-emea.demodomain.net port 80 (#0)
-   Trying 192.168.1.147... connected
- Connected to ad-emea.demodomain.net (192.168.1.147) port 80 (#0)
  > GET /testfast HTTP/1.1
  > User-Agent: Mozilla/5.0 (compatible; MSIE 6.0; Windows NT 6.0; SV1; .NET CLR 1
  .1.4325)
  > Host: ad-emea.demodomain.net
  > Accept: text/javascript, text/html, application/xml, text/xml, _/_
  > Accept-Language: en
  >
  < HTTP/1.1 200 OK
  < Server: nginx/0.8.54
  < Date: Thu, 17 Feb 2011 12:48:16 GMT
  < Content-Type: text/plain; charset=utf-8
  < Connection: keep-alive
  < Cache-Control: private
  < P3P: policyref="/w3c/p3p.xml", CP="NOI DSP COR NID PSAo OUR IND"
  < Content-Length: 11
  <
  Hello World\* Connection #0 to host ad-emea.demodomain.net left intact
- Closing connection #0
  RESULT: works ok, result is returned. timing ok.

curl --verbose http://ad-emea.demodomain.net/testslow
- About to connect() to ad-emea.demodomain.net port 80 (#0)
-   Trying 192.168.1.147... connected
- Connected to ad-emea.demodomain.net (192.168.1.147) port 80 (#0)
  > GET /testslow HTTP/1.1
  > User-Agent: Mozilla/5.0 (compatible; MSIE 6.0; Windows NT 6.0; SV1; .NET CLR 1
  .1.4325)
  > Host: ad-emea.demodomain.net
  > Accept: text/javascript, text/html, application/xml, text/xml, _/_
  > Accept-Language: en
  >
  < HTTP/1.1 200 OK
  < Server: nginx/0.8.54
  < Date: Thu, 17 Feb 2011 12:48:22 GMT
  < Content-Type: text/plain
  < Transfer-Encoding: chunked
  < Connection: keep-alive
  <
- Connection #0 to host ad-emea.demodomain.net left intact
- Closing connection #0
  RESULT: ERROR: no result text returned, timing ok

curl --verbose http://ad-emea.demodomain.net/testslow2
- About to connect() to ad-emea.demodomain.net port 80 (#0)
-   Trying 192.168.1.147... connected
- Connected to ad-emea.demodomain.net (192.168.1.147) port 80 (#0)
  > GET /testslow2 HTTP/1.1
  > User-Agent: Mozilla/5.0 (compatible; MSIE 6.0; Windows NT 6.0; SV1; .NET CLR 1
  .1.4325)
  > Host: ad-emea.demodomain.net
  > Accept: text/javascript, text/html, application/xml, text/xml, _/_
  > Accept-Language: en
  >
  < HTTP/1.1 200 OK
  < Server: nginx/0.8.54
  < Date: Thu, 17 Feb 2011 12:48:26 GMT
  < Content-Type: text/plain; charset=utf-8
  < Connection: keep-alive
  < Cache-Control: private
  < P3P: policyref="/w3c/p3p.xml", CP="NOI DSP COR NID PSAo OUR IND"
  < Content-Length: 11
  <
  Hello World\* Connection #0 to host ad-emea.demodomain.net left intact
- Closing connection #0
  RESULT: ERROR: result text ok, timing ERROR (as if no echo_sleep command)

my enviorment:
nginx version: nginx/0.8.54
built by gcc 4.4.3 (Ubuntu 4.4.3-4ubuntu5) 
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --pid-path=/var/run/nginx.pid --lock-path=/var/lock/nginx.lock --user=www-data --group=www-data --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --with-cc-opt=-O2 --with-http_gzip_static_module --with-http_ssl_module --with-http_geoip_module --add-module=/home/uporabnik/agentzh-echo-nginx-module-1c4e116

**Comment by euglv** [comment]
When using `echo_location` then headers are not forwarded properly.. 
`echo_sleep` is useless for this purpose.
This worked:
```
    access_by_lua_block { ngx.sleep(5) }
    proxy_pass http://svr_backend;
```
But this approach uses another module.

**Comment by agentzh** [comment]
@euglv `echo_location` registers a content handler for the `ngx_echo` module while `proxy_pass` registers another one for the `ngx_proxy` module. Every nginx location only allows one single module's content handler so only one of them wins here.

**Comment by bra-fsn** [comment]
> When using `echo_location` then headers are not forwarded properly.. `echo_sleep` is useless for this purpose.

@agentzh I think @euglv refers to this problem:

**This works:**

App returns header
```
$ curl -sv http://localhost:8000/app 2>&1 >/dev/null | grep test
< test: test header
$
```

With the following nginx config the same works through the proxy:
```nginx
location /foo {
    proxy_pass http://127.0.0.1:8000/app;
}
```

nginx listening on localhost:80:
```
$ curl -sv http://localhost/foo 2>&1 >/dev/null | grep test
< test: test header
$
```

**But this doesn't work:**

```nginx
location /proxy {
    proxy_pass http://127.0.0.1:8000/app;
}

location /foo {
    echo_sleep 1;
    echo_location /proxy;
    echo_sleep 1;
}
```

`test` header is not returned through `echo_location` and `proxy_pass`:
```
$ curl -sv http://localhost/foo 2>&1 >/dev/null | grep test
$
```
