### ISSUE TITLE
Can not be compiled with DDEBUG=2 defined.

### ISSUE THREAD

**Issue by amdei** [openresty/echo-nginx-module#52]
Fresh master branch.
Playing with other module ([replace-filter-nginx-module](https://github.com/openresty/replace-filter-nginx-module)), and enabled DDEBUG=2 for extra debug output found that echo-nginx-module can not be compiled with these settings.

configure command line:
`./configure --with-cc-opt='-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC -g -ggdb3 -O0 -DDEBUG -DDDEBUG=2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' --with-debug --with-pcre --with-pcre-jit --with-ipv6 --with-poll_module --add-module=.. --add-module=../lua-nginx-module --add-module=../echo-nginx-module`

Error message for make:
>`In file included from ../echo-nginx-module/src/ngx_http_echo_module.c:10:0:
../echo-nginx-module/src/ddebug.h:33:1: error: ‘inline’ is not at beginning of declaration [-Werror=old-style-declaration]
 static void ngx_inline
 ^
`

`# uname -a
Linux ng18 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`
`gcc version 4.9.2 (Debian 4.9.2-10)`

**Comment by amdei** [comment]
Fix is trivial - move ngx_inline to the beginning of declaration.

**Comment by agentzh** [comment]
@amdei Fixed in git master. Thanks for the report!
