### ISSUE TITLE
echo_before/after_body在rewrite下无效

### ISSUE THREAD

**Issue by ambjlon** [openresty/echo-nginx-module#61]
echo_before/after_body在proxy_pass下使用是有效的. 但是在rewrite下使用是无效的.

**Comment by agentzh** [comment]
@ambjlon Please, no Chinese here.

Please do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see http://openresty.org/en/community.html
