### ISSUE TITLE
Can't build with Nginx v1.12.0

### ISSUE THREAD

**Issue by dakanji** [openresty/echo-nginx-module#69]
I have seen the various issues and that there was a patch applied but want to flag that the latest release, v0.60, can't be compiled with Nginx v1.12.0.

Error message essentially the same as was with the previous issues raised with Nginx v1.11.x

**Comment by agentzh** [comment]
@dakanji Have you tried the latest git master branch? It should work.

**Comment by dakanji** [comment]
Probably does but decided to abandon the attempt to move to Nginx 1.12 for the time being as Ngx-Lua v10.8 (last actual release) fails to build as well.

Would take another look when Ngx-Lua v0.10.9 moves from RC status and the echo module is updated to v0.61.

Thanks.
