### ISSUE TITLE
什么时候可以支持较新版本的nginx，比如1.12.1

### ISSUE THREAD

**Issue by PoplarYang** [openresty/echo-nginx-module#72]

**Comment by agentzh** [comment]
@PoplarYang Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Regarding your question, I believe the git master branch already supports the latest nginx cores.
