### ISSUE TITLE
Using $echo_it inside if-clause doesn't work.

### ISSUE THREAD

**Issue by silentHoo** [openresty/echo-nginx-module#78]
I try to use `echo_foreach_split` to get each request header from the incoming request but only want to set one header on the response. Is this a bug or is this impossible this way?

I tried it like this with:

```
# curl -i localhost:8080/echoback -H 'any_specific_header_i_want_to_whitelist: any-value'

  location /echoback {
      echo_foreach_split '\n' $echo_client_request_headers;
        if ($echo_it ~ 'any_specific_header_i_want_to_whitelist') {
          echo "yep, found!";
          # $my_extracted_header_value = "any-value";
        }
      echo_end;

      # more_set_headers "any_specific_header_i_want_to_whitelist: $my_extracted_header_value";
    }
```

Isn't this possible due to the underlying pointer structure used here? Or I'm doing it wrong?

**Comment by duzhe** [comment]
nginx configuration is NOT a programing language， you'd better not putting complex logic in it。try lua-nginx-module。

in nginx configuration file, config commands run at several phase sequentially, "if" command run at REWRITE phase, "echo_foreach_split" command run at CONTENT phase, so , it not working as your expected。

**Comment by silentHoo** [comment]
Thanks @duzhe I've mixed it together, now I've found a working solution with lua.
